---
- name: Restart SSH
  ansible.builtin.service:
    name: "{{ security_effective_ssh_service | default('sshd') }}"
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Restart rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: restarted
