---
# Global security defaults. Override per-environment or host as needed.
security_ssh_port: 1022
security_ssh_permit_root_login: "no"
security_ssh_password_authentication: "no"
security_ssh_allow_users: []
security_ssh_allow_groups: []
security_ssh_banner: false
security_firewall_enabled: true
security_firewall_allowed_tcp_ports:
  - "{{ security_ssh_port }}"
security_firewall_allowed_udp_ports: []
security_fail2ban_enabled: true
security_fail2ban_maxretry: 5
security_fail2ban_findtime: 600
security_fail2ban_bantime: 3600
security_automatic_updates_enabled: true
security_unattended_upgrades_email: ""
security_unattended_upgrades_auto_reboot: true
security_unattended_upgrades_reboot_time: "02:30"
security_disable_services: []
security_syslog_remote_host: ""
security_syslog_remote_port: 514
security_syslog_protocol: udp

# Docker defaults. Adjust per environment as needed.
docker_users: []
docker_directories:
  - path: /opt/docker
    owner: root
    group: docker
    mode: "0755"
docker_daemon_config:
  log-driver: json-file
  log-opts:
    max-size: "10m"
    max-file: "5"
