services:
  n8n:
    image: n8nio/n8n:2.35.0
    container_name: n8n
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - n8n_network
      - traefik_network
    labels:
      com.homelab.service: "n8n"
      com.homelab.maintainer: "homelab"

      # Turns on Traefik for this specific container
      traefik.enable: "true"
      #Entrypoint for secure traffic
      traefik.http.routers.n8n.entrypoints: "websecure"
      #Use Cloudflare resolver to manage TLS certificates
      traefik.http.routers.n8n.tls.certresolver: "cloudflare"
      #Domain routing rule
      traefik.http.routers.n8n.rule: "Host(`n8n.homedev.landingsnet.com`)"
      #Internal port where service is listening
      traefik.http.services.n8n.loadbalancer.server.port: "5678"
      homepage.name: "n8n"
      homepage.description: "Workflow automation"
      homepage.icon: "n8n.png"
      homepage.group: "Automation"
      homepage.href: "https://n8n.homedev.landingsnet.com"

volumes:
  n8n_data:
    name: n8n_data

networks:
  n8n_network:
    external: true
  traefik_network:
    external: true


