services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - 9443:9443
    networks:
      - portainer_network
      - traefik_network
    labels:
      com.homelab.service: "portainer"
      com.homelab.maintainer: "homelab"
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.tls.certresolver: "cloudflare"
      traefik.http.routers.portainer.rule: "Host(`portainer.homedev.landingsnet.com`)"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
      homepage.name: "Portainer"
      homepage.description: "Docker container management"
      homepage.icon: "portainer.png"
      homepage.group: "Infrastructure"
      homepage.href: "https://portainer.homedev.landingsnet.com"

volumes:
  portainer_data:
    name: portainer_data


networks:
  portainer_network:
    external: true
  traefik_network:
    external: true