- resources:
    cpu: true
    memory: true
    disk: /

- search:
    provider: custom
    url: https://www.google.com/search?udm=50&aep=11&q=
    target: _self
    focus: false
    showSearchSuggestions: true
    suggestionUrl: https://suggestqueries.google.com/complete/search?client=chrome&q=

- datetime:
    text_size: xl
    format:
      timeStyle: short
      dateStyle: short
      hour12: true
