services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    labels:
      com.homelab.service: "homeassistant"
      com.homelab.maintainer: "homelab"
      traefik.enable: "true"
      traefik.http.routers.homeassistant.rule: "Host(`homeassistant.homedev.landingsnet.com`)"
      traefik.http.routers.homeassistant.entrypoints: "websecure"
      traefik.http.routers.homeassistant.tls.certresolver: "cloudflare"
      traefik.http.services.homeassistant.loadbalancer.server.url: "http://host.docker.internal:8123"
      homepage.name: "Home Assistant"
      homepage.description: "Home automation platform"
      homepage.icon: "home-assistant.png"
      homepage.group: "Home"
      homepage.href: "https://homeassistant.homedev.landingsnet.com"

    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      TZ: America/New_York


  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2026.1
    volumes:
      - ./config/esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    labels:
      com.homelab.service: "esphome"
      com.homelab.maintainer: "homelab"
      traefik.enable: "true"
      traefik.http.routers.esphome.rule: "Host(`esphome.homedev.landingsnet.com`)"
      traefik.http.routers.esphome.entrypoints: "websecure"
      traefik.http.routers.esphome.tls.certresolver: "cloudflare"
      traefik.http.services.esphome.loadbalancer.server.url: "http://host.docker.internal:6052"
      homepage.name: "ESPHome"
      homepage.description: "ESP microcontroller firmware management"
      homepage.icon: "esphome.png"
      homepage.group: "Home"
      homepage.href: "https://esphome.homedev.landingsnet.com"
    env_file:
      - .env
      