---
- name: Ensure UFW default incoming policy is deny
  community.general.ufw:
    direction: incoming
    policy: deny

- name: Ensure UFW default outgoing policy is allow
  community.general.ufw:
    direction: outgoing
    policy: allow

- name: Allow required TCP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
    comment: Managed by Ansible (homelab security role)
  loop: "{{ security_firewall_allowed_tcp_ports | unique }}"

- name: Allow required UDP ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: udp
    comment: Managed by Ansible (homelab security role)
  loop: "{{ security_firewall_allowed_udp_ports | default([]) | unique }}"

- name: Ensure UFW is enabled
  community.general.ufw:
    state: enabled
    logging: on
