services:
  actual_server:
    container_name: actualbudget
    image: docker.io/actualbudget/actual-server:latest@sha256:6478d9ddfc0924479c09e6699c205e354c6f2216dfe7de3c0fb7b590d6edcdc5
    labels:
      com.homelab.service: "actualbudget"
      com.homelab.maintainer: "homelab"
      traefik.enable: "true"
      traefik.http.routers.actualbudget.entrypoints: "websecure"
      traefik.http.routers.actualbudget.tls.certresolver: "cloudflare"
      traefik.http.routers.actualbudget.rule: "Host(`actualbudget.prod.landingsnet.com`)"
      traefik.http.services.actualbudget.loadbalancer.server.port: "5006"
      homepage.name: "Actual Budget"
      homepage.description: "Personal finance and budgeting"
      homepage.icon: "actual-budget.png"
      homepage.group: "Finance"
      homepage.href: "https://actualbudget.prod.landingsnet.com"
    env_file:
      - .env
    volumes:
      # '/data' is the path Actual will look for its files in by default, so leave that as-is.
      - ./actual-data:/data
    networks:
      - traefik_network
      - actualbudget_network
    healthcheck:
      # Enable health check for the instance
      test: ['CMD-SHELL', 'node src/scripts/health-check.js']
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 20s
    restart: unless-stopped

networks:
  actualbudget_network:
    external: true
  traefik_network:
    external: true